[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xbee-python"
version = "2.0.0a"
description = "XBee serial communication library"
requires-python = ">=3.8"
authors = [{ name = "Joshua Ho" }]
dependencies = [
  "serial-io>=0.1.0a",
  "xbee-logger>=0.1.0a"
]

[tool.setuptools.packages.find]
where = ["src"]